kind: Service
apiVersion: v1
metadata:
  #Service name
  name: birthday-api-svc
spec:
  selector:
    app: birthday-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
